### ISSUE TITLE
Challenge 1

### ISSUE THREAD

**Issue by MKhodagholi** [BehnoodAmini/ava#2]
دیپلوی صورت گرفته درست نیست و صفحه سفید نمایش می‌دهد.
لطفا بررسی و درست کنید.

![Screenshot from 2023-08-19 14-51-39](https://github.com/BehnoodAmini/Ava-RoshanInternshipProject/assets/83423435/50832ec6-83f3-4548-9e63-5688abd12ab5)

**Comment by BehnoodAmini** [comment]
> 



> دیپلوی صورت گرفته درست نیست و صفحه سفید نمایش می‌دهد. لطفا بررسی و درست کنید.
> 
> ![Screenshot from 2023-08-19 14-51-39](https://user-images.githubusercontent.com/83423435/261795009-50832ec6-83f3-4548-9e63-5688abd12ab5.png)

با کمک vercel حل شد.

**Comment by MKhodagholi** [comment]
دست شما درد نکنه.
اصلاحاتی که به نظرم نیاز هست انجام بدید این ها است:
صفحه آرشیو اصلا شبیه طراحی نیست. لطفا دوباره بررسی کنید
<img width="1438" alt="Screen Shot 2023-08-21 at 8 25 43 PM" src="https://github.com/BehnoodAmini/ava/assets/83423435/b7a6d89d-8a47-424b-ad66-189ce7fd30df">

<img width="1122" alt="Screen Shot 2023-08-21 at 8 26 19 PM" src="https://github.com/BehnoodAmini/ava/assets/83423435/b45f216e-707d-4f31-9fdb-d143da6f52e2">

برای صفحه اصلی هم قسمت ضبط صدا دارای آیکون هست ولی نمیدونم چرا شما نوشته گزاشتید بجاش.

<img width="694" alt="Screen Shot 2023-08-21 at 8 27 59 PM" src="https://github.com/BehnoodAmini/ava/assets/83423435/ae43a35b-db3b-4dd7-a742-bf2f2136e3da">

برای قسمت لینک هم شبیه طراحی دقیق پیاده سازی نشده.
<img width="751" alt="Screen Shot 2023-08-21 at 8 29 06 PM" src="https://github.com/BehnoodAmini/ava/assets/83423435/d7fca894-d24c-45cc-8375-fb49d1f4d9ec">

**Comment by BehnoodAmini** [comment]
> دست شما درد نکنه. اصلاحاتی که به نظرم نیاز هست انجام بدید این ها است: صفحه آرشیو اصلا شبیه طراحی نیست. لطفا دوباره بررسی کنید <img alt="Screen Shot 2023-08-21 at 8 25 43 PM" width="1438" src="https://user-images.githubusercontent.com/83423435/262092498-b7a6d89d-8a47-424b-ad66-189ce7fd30df.png">
> 
> <img alt="Screen Shot 2023-08-21 at 8 26 19 PM" width="1122" src="https://user-images.githubusercontent.com/83423435/262092510-b45f216e-707d-4f31-9fdb-d143da6f52e2.png">
> برای صفحه اصلی هم قسمت ضبط صدا دارای آیکون هست ولی نمیدونم چرا شما نوشته گزاشتید بجاش.
> 
> <img alt="Screen Shot 2023-08-21 at 8 27 59 PM" width="694" src="https://user-images.githubusercontent.com/83423435/262092786-ae43a35b-db3b-4dd7-a742-bf2f2136e3da.png">
> برای قسمت لینک هم شبیه طراحی دقیق پیاده سازی نشده. <img alt="Screen Shot 2023-08-21 at 8 29 06 PM" width="751" src="https://user-images.githubusercontent.com/83423435/262093037-d7fca894-d24c-45cc-8375-fb49d1f4d9ec.png">

با سلام و خسته نباشید مشکلات در همه مرورگر ها فیکس شدند. متن به جای علامت ریکورد بخاطر گرفتن permission بود که با لوگو میکروفون جایگزین شد. کد فیکس شده را در branch چلنج دوم یا مستر ببینید. با تشکر

**Comment by MKhodagholi** [comment]
تشکر
